"""
Robust JSON parser with automatic fixing for common model errors.
"""

import json
import re


def extract_json_from_text(text):
    """
    Extract JSON object from text that might contain extra content.
    
    Handles:
    - Extra text before/after JSON
    - Multiple JSON objects (returns first)
    """
    # Find first { and last }
    start = text.find('{')
    end = text.rfind('}')
    
    if start == -1 or end == -1 or start >= end:
        return None
    
    return text[start:end+1]


def fix_common_json_errors(json_str):
    """
    Fix common JSON syntax errors generated by models.
    """
    # Remove trailing commas before } or ]
    json_str = re.sub(r',\s*}', '}', json_str)
    json_str = re.sub(r',\s*]', ']', json_str)
    
    # Replace single quotes with double quotes (but be careful with apostrophes in text)
    # Only replace quotes around keys and at start/end of values
    json_str = re.sub(r"'(\w+)':", r'"\1":', json_str)  # Keys
    
    # Fix missing quotes around null, true, false
    json_str = re.sub(r':\s*None\b', ': null', json_str)
    json_str = re.sub(r':\s*True\b', ': true', json_str)
    json_str = re.sub(r':\s*False\b', ': false', json_str)
    
    return json_str


def parse_model_output(model_output, strict=False):
    """
    Robust JSON parser for model outputs.
    
    Args:
        model_output: String output from model
        strict: If True, raise exception on failure. If False, return None.
    
    Returns:
        Parsed JSON dict, or None if parsing fails
    """
    if not model_output or not isinstance(model_output, str):
        if strict:
            raise ValueError("Empty or invalid model output")
        return None
    
    # Try 1: Direct parsing (model generated perfect JSON)
    try:
        return json.loads(model_output)
    except json.JSONDecodeError:
        pass
    
    # Try 2: Strip whitespace
    try:
        return json.loads(model_output.strip())
    except json.JSONDecodeError:
        pass
    
    # Try 3: Extract JSON from text with extra content
    extracted = extract_json_from_text(model_output)
    if extracted:
        try:
            return json.loads(extracted)
        except json.JSONDecodeError:
            pass
        
        # Try 4: Fix common errors in extracted JSON
        try:
            fixed = fix_common_json_errors(extracted)
            return json.loads(fixed)
        except json.JSONDecodeError:
            pass
    
    # Try 5: Fix common errors in original text
    try:
        fixed = fix_common_json_errors(model_output)
        return json.loads(fixed)
    except json.JSONDecodeError:
        pass
    
    # All attempts failed
    if strict:
        raise ValueError(f"Could not parse JSON from model output: {model_output[:100]}...")
    
    return None


def validate_event_output(parsed_json):
    """
    Validate and fill missing required fields for event output.
    """
    required_fields = ['action', 'date', 'time', 'attendees', 'location', 
                      'duration', 'recurrence', 'notes']
    
    # Ensure all fields exist
    for field in required_fields:
        if field not in parsed_json:
            parsed_json[field] = None
    
    # Validate types
    if parsed_json.get('attendees') is not None and not isinstance(parsed_json['attendees'], list):
        # Convert string to list if needed
        if isinstance(parsed_json['attendees'], str):
            parsed_json['attendees'] = [parsed_json['attendees']]
    
    return parsed_json


# Example usage
if __name__ == "__main__":
    # Test cases
    test_cases = [
        # Valid JSON
        '{"action": "Meeting", "date": "2024-01-29"}',
        
        # Extra text
        'Here is the result: {"action": "Meeting", "date": "2024-01-29"}',
        'The parsed event is {"action": "Meeting", "date": "2024-01-29"} done',
        
        # Trailing comma
        '{"action": "Meeting", "date": "2024-01-29",}',
        
        # Single quotes
        "{'action': 'Meeting', 'date': '2024-01-29'}",
        
        # Python None instead of null
        '{"action": "Meeting", "attendees": None}',
        
        # Invalid
        'Not JSON at all',
        '{"action": "Meeting"',  # Incomplete
    ]
    
    print("Testing JSON parser:\n")
    for i, test in enumerate(test_cases, 1):
        print(f"[Test {i}] {test[:50]}...")
        result = parse_model_output(test)
        if result:
            print(f"  ✅ Parsed: {result}")
        else:
            print(f"  ❌ Failed to parse")
        print()
