// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHpGT60XTGK9mUAzSAVLeoucdKQR-Rnc',
    appId: '1:445439637163:web:d5ad8284c8888c74d469ee',
    messagingSenderId: '445439637163',
    projectId: 'orbit-41815',
    authDomain: 'orbit-41815.firebaseapp.com',
    storageBucket: 'orbit-41815.firebasestorage.app',
    measurementId: 'G-3QRBDJ5Q8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHhhbyb9oOU8mmYnaff_i-c7u9Iw5abg',
    appId: '1:445439637163:android:9fa777a6a0823a1fd469ee',
    messagingSenderId: '445439637163',
    projectId: 'orbit-41815',
    storageBucket: 'orbit-41815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1A7Z6eOI6UIFIgx3OXdmoQR0aPx9mGAI',
    appId: '1:445439637163:ios:f8daccdd172a0cf4d469ee',
    messagingSenderId: '445439637163',
    projectId: 'orbit-41815',
    storageBucket: 'orbit-41815.firebasestorage.app',
    iosBundleId: 'com.orbit.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1A7Z6eOI6UIFIgx3OXdmoQR0aPx9mGAI',
    appId: '1:445439637163:ios:f8daccdd172a0cf4d469ee',
    messagingSenderId: '445439637163',
    projectId: 'orbit-41815',
    storageBucket: 'orbit-41815.firebasestorage.app',
    iosBundleId: 'com.orbit.calendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIHpGT60XTGK9mUAzSAVLeoucdKQR-Rnc',
    appId: '1:445439637163:web:0cad3b78bc7c2a75d469ee',
    messagingSenderId: '445439637163',
    projectId: 'orbit-41815',
    authDomain: 'orbit-41815.firebaseapp.com',
    storageBucket: 'orbit-41815.firebasestorage.app',
    measurementId: 'G-MFJ0Z1E4Q8',
  );

}