  name: Flutter Lint & Analyze

  on:
    pull_request:
      paths:
        - '**/*.dart'
        - 'lib/**'
        - 'test/**'
    push:
      branches:
        - main

  jobs:
    analyze:
      name: Lint and tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            cache: true
        - name: Install dependencies
          run: flutter pub get

        - name: Format check
          run: dart format --set-exit-if-changed .

        - name: Flutter analyze
          run: flutter analyze --no-fatal-infos --no-fatal-warnings

        - name: Dart analyze with stricter rules
          run: dart analyze --fatal-infos --no-fatal-warnings

        - name: Run tests
          run: flutter test --coverage
