  # This GitHub Actions workflow lints and analyzes a Flutter project. If ur code
  # is not properly formatted, or if there are any analyzer issues, the workflow
  # will fail. It also runs tests and collects coverage information. Good Luck :)
  name: Flutter Lint & Analyze

  on:
    pull_request:
    push:
      branches:
        - main

  jobs:
    analyze:
      name: Lint and tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v6

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            cache: true
        - name: Install dependencies
          run: flutter pub get

        - name: Format check
          run: dart format --set-exit-if-changed .

        - name: Flutter analyze
          run: flutter analyze --no-fatal-infos --no-fatal-warnings

        - name: Dart analyze with stricter rules
          run: dart analyze --fatal-infos --no-fatal-warnings

        - name: Run tests
          run: flutter test --coverage
